## This is a work notebook to try things out for the week 1 quiz.


In [2]:
import numpy as np
r = np.arange(36)
r = r.reshape(6,6)
s = r.copy()


![Question 11](Question_11.png)

In [3]:
print('r:', r, '\n')
print('slice:', s.reshape(36)[::7])

r: [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]] 

slice: [ 0  7 14 21 28 35]



![Question 12](Question_12.png)

In [5]:
print('Answer 1:', r[[2,3],[2,3]])
print('Answer 2:', r[2::2,2::2])
print('Answer 3:', r[2:4,2:4])
print('Answer 4:', r[::2,::2])

Answer 1: [14 21]
Answer 2: [[14 16]
 [26 28]]
Answer 3: [[14 15]
 [20 21]]
Answer 4: [[ 0  2  4]
 [12 14 16]
 [24 26 28]]
